export const TYPES = {
  NO_DATA: "TYPES_NO_DATA",
  READ_PRODUCTS: "READ_PRODUCTS",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_ONE_FROM_CART: "REMOVE_ONE_FROM_CART",
  REMOVE_ALL_FROM_CART: "REMOVE_ALL_FROM_CART",
  SET_CLIENT: "SET_CLIENT",
  CLEAR_CART: "CLEAR_CART",
};